apiVersion: apps/v1
kind: Deployment
metadata:
  name: phone-validator-frontend
  labels:
    app: phone-validator-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phone-validator-frontend
  strategy: 
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: phone-validator-frontend
    spec:
      containers:
      - image: johnylima/phone-validator-frontend-2:5
        name: phone-validator-frontend
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
            - name: frontend-port
              containerPort: 8081
              hostPort: 8081

status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-phone-validator-frontend
  labels:
    app: phone-validator-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: phone-validator-frontend
